use_frameworks!

target 'YYOCFramework_Example' do
  pod 'YYOCFramework', :path => '../'

  target 'YYOCFramework_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
